<?php
$_helper = $this->helper('catalog/output');
$_category = $this->getCurrentCategory();
$_imgHtml = '';
if ($_imgUrl = $_category->getImageUrl()) {
    $_imgHtml = '<p class="category-image"><img src="' . $_imgUrl . '" alt="' . $this->htmlEscape($_category->getName()) . '" title="' . $this->htmlEscape($_category->getName()) . '" /></p>';
    $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
}
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if ($_imgUrl): ?>
    <?php echo $_imgHtml ?>
<?php endif; ?>

<?php if ($_description = $this->getCurrentCategory()->getDescription()): ?>
    <div class="category-description std">
        <?php if ($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
            <a href="<?php echo $this->getRssLink() ?>"
               class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
        <?php endif; ?>
        <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
        <?php /* if ($de = trim($_helper->categoryAttribute($_category, $_description, 'description'))): ?>
            <p><?php echo $de; ?></p>
        <?php endif;*/
        ?>
    </div>
<?php endif; ?>

<?php if ($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif ($this->isMixedMode()): ?>
    <p class="category-image">
        <?php echo $this->getCmsBlockHtml() ?>
    </p>
    <?php echo $this->getProductListHtml() ?>

<?php
else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
